// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/product/v1/product_service.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice     string                 `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"` // decimal string, e.g. "19.99"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetBasePrice() string {
	if x != nil {
		return x.BasePrice
	}
	return ""
}

type CreateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReply) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{3}
}

type ActivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductRequest) Reset() {
	*x = ActivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductRequest) ProtoMessage() {}

func (x *ActivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductRequest.ProtoReflect.Descriptor instead.
func (*ActivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ActivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductReply) Reset() {
	*x = ActivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductReply) ProtoMessage() {}

func (x *ActivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductReply.ProtoReflect.Descriptor instead.
func (*ActivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{5}
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type DeactivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductReply) Reset() {
	*x = DeactivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductReply) ProtoMessage() {}

func (x *DeactivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductReply.ProtoReflect.Descriptor instead.
func (*DeactivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{7}
}

type ArchiveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductRequest) Reset() {
	*x = ArchiveProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductRequest) ProtoMessage() {}

func (x *ArchiveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductRequest.ProtoReflect.Descriptor instead.
func (*ArchiveProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ArchiveProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductReply) Reset() {
	*x = ArchiveProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductReply) ProtoMessage() {}

func (x *ArchiveProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductReply.ProtoReflect.Descriptor instead.
func (*ArchiveProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{9}
}

type ApplyDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Percentage    string                 `protobuf:"bytes,2,opt,name=percentage,proto3" json:"percentage,omitempty"` // whole-number percentage, e.g. "20"
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountRequest) Reset() {
	*x = ApplyDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountRequest) ProtoMessage() {}

func (x *ApplyDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountRequest.ProtoReflect.Descriptor instead.
func (*ApplyDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ApplyDiscountRequest) GetPercentage() string {
	if x != nil {
		return x.Percentage
	}
	return ""
}

func (x *ApplyDiscountRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ApplyDiscountRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ApplyDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountReply) Reset() {
	*x = ApplyDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountReply) ProtoMessage() {}

func (x *ApplyDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountReply.ProtoReflect.Descriptor instead.
func (*ApplyDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{11}
}

type RemoveDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountRequest) Reset() {
	*x = RemoveDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountRequest) ProtoMessage() {}

func (x *RemoveDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountRequest.ProtoReflect.Descriptor instead.
func (*RemoveDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountReply) Reset() {
	*x = RemoveDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountReply) ProtoMessage() {}

func (x *RemoveDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountReply.ProtoReflect.Descriptor instead.
func (*RemoveDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{13}
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductSummary      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListProductsReply) GetProducts() []*ProductSummary {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice       string                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice  string                 `protobuf:"bytes,6,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	DiscountPercent *string                `protobuf:"bytes,7,opt,name=discount_percent,json=discountPercent,proto3,oneof" json:"discount_percent,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{18}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetBasePrice() string {
	if x != nil {
		return x.BasePrice
	}
	return ""
}

func (x *Product) GetEffectivePrice() string {
	if x != nil {
		return x.EffectivePrice
	}
	return ""
}

func (x *Product) GetDiscountPercent() string {
	if x != nil && x.DiscountPercent != nil {
		return *x.DiscountPercent
	}
	return ""
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category       string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice      string                 `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice string                 `protobuf:"bytes,5,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductSummary) Reset() {
	*x = ProductSummary{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSummary) ProtoMessage() {}

func (x *ProductSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSummary.ProtoReflect.Descriptor instead.
func (*ProductSummary) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{19}
}

func (x *ProductSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductSummary) GetBasePrice() string {
	if x != nil {
		return x.BasePrice
	}
	return ""
}

func (x *ProductSummary) GetEffectivePrice() string {
	if x != nil {
		return x.EffectivePrice
	}
	return ""
}

func (x *ProductSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_product_v1_product_service_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_service_proto_rawDesc = "" +
	"\n" +
	"&proto/product/v1/product_service.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"base_price\x18\x04 \x01(\tR\tbasePrice\"3\n" +
	"\x12CreateProductReply\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xbc\x01\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x02R\bcategory\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_category\"\x14\n" +
	"\x12UpdateProductReply\"7\n" +
	"\x16ActivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x16\n" +
	"\x14ActivateProductReply\"9\n" +
	"\x18DeactivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x18\n" +
	"\x16DeactivateProductReply\"6\n" +
	"\x15ArchiveProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x15\n" +
	"\x13ArchiveProductReply\"\xc7\x01\n" +
	"\x14ApplyDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\tR\n" +
	"percentage\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x14\n" +
	"\x12ApplyDiscountReply\"6\n" +
	"\x15RemoveDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x15\n" +
	"\x13RemoveDiscountReply\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"@\n" +
	"\x0fGetProductReply\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"m\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"s\n" +
	"\x11ListProductsReply\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.product.v1.ProductSummaryR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x86\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\tR\tbasePrice\x12'\n" +
	"\x0feffective_price\x18\x06 \x01(\tR\x0eeffectivePrice\x12.\n" +
	"\x10discount_percent\x18\a \x01(\tH\x00R\x0fdiscountPercent\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_discount_percent\"\xeb\x01\n" +
	"\x0eProductSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"base_price\x18\x04 \x01(\tR\tbasePrice\x12'\n" +
	"\x0feffective_price\x18\x05 \x01(\tR\x0eeffectivePrice\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x87\x06\n" +
	"\x0eProductService\x12Q\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a\x1e.product.v1.CreateProductReply\x12Q\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a\x1e.product.v1.UpdateProductReply\x12W\n" +
	"\x0fActivateProduct\x12\".product.v1.ActivateProductRequest\x1a .product.v1.ActivateProductReply\x12]\n" +
	"\x11DeactivateProduct\x12$.product.v1.DeactivateProductRequest\x1a\".product.v1.DeactivateProductReply\x12T\n" +
	"\x0eArchiveProduct\x12!.product.v1.ArchiveProductRequest\x1a\x1f.product.v1.ArchiveProductReply\x12Q\n" +
	"\rApplyDiscount\x12 .product.v1.ApplyDiscountRequest\x1a\x1e.product.v1.ApplyDiscountReply\x12T\n" +
	"\x0eRemoveDiscount\x12!.product.v1.RemoveDiscountRequest\x1a\x1f.product.v1.RemoveDiscountReply\x12H\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1b.product.v1.GetProductReply\x12N\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a\x1d.product.v1.ListProductsReplyB>Z<github.com/tshubham2/catalog-proj/proto/product/v1;productv1b\x06proto3"

var (
	file_proto_product_v1_product_service_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_service_proto_rawDescData []byte
)

func file_proto_product_v1_product_service_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_service_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)))
	})
	return file_proto_product_v1_product_service_proto_rawDescData
}

var file_proto_product_v1_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_product_v1_product_service_proto_goTypes = []any{
	(*CreateProductRequest)(nil),     // 0: product.v1.CreateProductRequest
	(*CreateProductReply)(nil),       // 1: product.v1.CreateProductReply
	(*UpdateProductRequest)(nil),     // 2: product.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),       // 3: product.v1.UpdateProductReply
	(*ActivateProductRequest)(nil),   // 4: product.v1.ActivateProductRequest
	(*ActivateProductReply)(nil),     // 5: product.v1.ActivateProductReply
	(*DeactivateProductRequest)(nil), // 6: product.v1.DeactivateProductRequest
	(*DeactivateProductReply)(nil),   // 7: product.v1.DeactivateProductReply
	(*ArchiveProductRequest)(nil),    // 8: product.v1.ArchiveProductRequest
	(*ArchiveProductReply)(nil),      // 9: product.v1.ArchiveProductReply
	(*ApplyDiscountRequest)(nil),     // 10: product.v1.ApplyDiscountRequest
	(*ApplyDiscountReply)(nil),       // 11: product.v1.ApplyDiscountReply
	(*RemoveDiscountRequest)(nil),    // 12: product.v1.RemoveDiscountRequest
	(*RemoveDiscountReply)(nil),      // 13: product.v1.RemoveDiscountReply
	(*GetProductRequest)(nil),        // 14: product.v1.GetProductRequest
	(*GetProductReply)(nil),          // 15: product.v1.GetProductReply
	(*ListProductsRequest)(nil),      // 16: product.v1.ListProductsRequest
	(*ListProductsReply)(nil),        // 17: product.v1.ListProductsReply
	(*Product)(nil),                  // 18: product.v1.Product
	(*ProductSummary)(nil),           // 19: product.v1.ProductSummary
	(*timestamppb.Timestamp)(nil),    // 20: google.protobuf.Timestamp
}
var file_proto_product_v1_product_service_proto_depIdxs = []int32{
	20, // 0: product.v1.ApplyDiscountRequest.start_date:type_name -> google.protobuf.Timestamp
	20, // 1: product.v1.ApplyDiscountRequest.end_date:type_name -> google.protobuf.Timestamp
	18, // 2: product.v1.GetProductReply.product:type_name -> product.v1.Product
	19, // 3: product.v1.ListProductsReply.products:type_name -> product.v1.ProductSummary
	20, // 4: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	20, // 6: product.v1.ProductSummary.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2,  // 8: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	4,  // 9: product.v1.ProductService.ActivateProduct:input_type -> product.v1.ActivateProductRequest
	6,  // 10: product.v1.ProductService.DeactivateProduct:input_type -> product.v1.DeactivateProductRequest
	8,  // 11: product.v1.ProductService.ArchiveProduct:input_type -> product.v1.ArchiveProductRequest
	10, // 12: product.v1.ProductService.ApplyDiscount:input_type -> product.v1.ApplyDiscountRequest
	12, // 13: product.v1.ProductService.RemoveDiscount:input_type -> product.v1.RemoveDiscountRequest
	14, // 14: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	16, // 15: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	1,  // 16: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductReply
	3,  // 17: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductReply
	5,  // 18: product.v1.ProductService.ActivateProduct:output_type -> product.v1.ActivateProductReply
	7,  // 19: product.v1.ProductService.DeactivateProduct:output_type -> product.v1.DeactivateProductReply
	9,  // 20: product.v1.ProductService.ArchiveProduct:output_type -> product.v1.ArchiveProductReply
	11, // 21: product.v1.ProductService.ApplyDiscount:output_type -> product.v1.ApplyDiscountReply
	13, // 22: product.v1.ProductService.RemoveDiscount:output_type -> product.v1.RemoveDiscountReply
	15, // 23: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductReply
	17, // 24: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsReply
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_service_proto_init() }
func file_proto_product_v1_product_service_proto_init() {
	if File_proto_product_v1_product_service_proto != nil {
		return
	}
	file_proto_product_v1_product_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_product_v1_product_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_service_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_service_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_service_proto = out.File
	file_proto_product_v1_product_service_proto_goTypes = nil
	file_proto_product_v1_product_service_proto_depIdxs = nil
}
